DEBUG = True

DOCUMENT_LABELS = [-1, 1]
SENTENCE_LABELS = [-1, 1]

STRUCTURED_JOINT = "structured-joint"
DOCUMENT_CLASSIFIER = "document-classifier"
SENTENCE_CLASSIFIER = "sentence-classifier"
SENTENCE_STRUCTURED = "sentence-structured"
MODELS = (STRUCTURED_JOINT, DOCUMENT_CLASSIFIER,
          SENTENCE_CLASSIFIER, SENTENCE_STRUCTURED)

DATA_PATH = "./data/"
MODELS_PATH = "./models/"
# BASIC_MODELS_PATH = MODELS_PATH + "basic/"
# ADVANCED_MODELS_PATH = MODELS_PATH + "advanced/"
TEST_PATH = "./test/"
# BASIC_TEST_PATH = TEST_PATH + "basic/"
# ADVANCED_TEST_PATH = TEST_PATH + "advanced/"
# COMP_PATH = "./comp/"
# BASIC_COMP_PATH = COMP_PATH + "basic/"
# ADVANCED_COMP_PATH = COMP_PATH + "advanced/"